name: Sincronitzar a IlernaDAW

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout origen
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Arxius sincronitzats
        env:
          API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Clona el destí usant el token que acabes de crear
          git clone https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/ilernadaw/ilernadaw.github.io.git desti

          # Sincronitza fitxers (això esborra al destí el que no estigui a l'origen)
          rsync -av --delete --exclude '.git' --exclude '.github' ./ desti/

          cd desti
          git add .
          # Només fem el push si realment hi ha canvis per evitar errors buits
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sincronització automàtica: $(date)"
            git push origin main
          else
            echo "No hi ha canvis per sincronitzar."
          fi